import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { connect } from "react-redux"
import Header from '../components/header/Header'

function Home({ name }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

<Header />
      <main className={styles.main}>
        <h1>Movie-hub app</h1>
        <h1>Hello {name}</h1>
        </main>
    </div>

  )
}

const mapToStateProps = state => {
  return {
    ...state,
    name: state.name
  }
}

export default connect(mapToStateProps)(Home);